### PR TITLE
Async field resolution support

### PR DESCRIPTION
**Pull request by scmccart**
Hey, here's a first take of supporting asynchronous field resolution. I chose to keep the synchronous method in place and async support beside it because I believe most use cases end up requiring both. I'm happy to add tests and examples of use, but I wanted to check if the contribution is welcome, and what was thought of the approach first.

### CODE REVIEW

**Comment by joemcbride** [comment]
Certainly welcome, thanks!  I know @james-andrewsmith was also working on something like this.

I agree that in almost every scenario you would need/want both sync and async.  I'm partial to the idea of keeping a single resolve though.  I'll pull this down and play with it a bit.

**Comment by joemcbride** [comment]
Opened #8

**Comment by james-andrewsmith** [comment]
@joemcbride 
@scmccart 

Nice!

I've got to cleanup what I've done (this is on the whole neater than my very quick take) however a lot of the actual task casting / whenall looks similar, I'll through up what I have on a fork so it makes for easier discussion. 

The key difference is I've kept a single resolve, and I'm just checking if the resolve is a task. 

I updated some of the tests to have a mix of Sync/Async resolution, at the very least we'll be able to use those tests.

**Comment by james-andrewsmith** [comment]
@joemcbride @scmccart 

Hey Guys - I've opened another PR to help with a discussion about Resolve & ResolveAsync vs Execute & ExecuteAsync

**Comment by scmccart** [comment]
Hey, I've moved this to a single resolve that isn't specifically dependent on `Task<object>`, but can use `Task<Human>` and `Task<Droid>`.

**Comment by joemcbride** [comment]
:+1: I like that change from `Task<T>` to `Task`.  Can you rename the `Execute` in `IDocumentExecutor` to `ExecuteAsync`?  After that I think we can pull this in.

**Comment by moserware** [comment]
I'm still getting up to speed on this, but I agree that `async` support would be great! What do you think about supporting [CancellationToken](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtoken(v=vs.110).aspx)s? I think it'd be nice to have some form timeout support (e.g. to prevent Denial Of Service attacks with deeply nested queries since they're coming from a possibly untrusted client) and a simple CancellationToken support combined with a [Task.Delay](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.delay(v=vs.110).aspx) could help with that.

That is, we could kick off the ExecuteAsync and a `Task.Delay`. If the `Task.Delay` finishes first, then we cancel the query by signaling the [CancellationTokenSource](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx)

Thoughts?

**Comment by scmccart** [comment]
@joemcbride Execute is now ExecuteAsync.

**Comment by scmccart** [comment]
@moserware I do like having the option of a `CancellationToken`, and it's usually best practice. Seems that it could short circuit the  `DocumentExecutor` and also be available in the `ResolveFieldContext`.

**Comment by joemcbride** [comment]
Created #16 to track cancellation/timeout

**Pull request merged**
